version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 25
    commands:
      - node -v
      - npm -v
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --configuration production
      - ls -lrat
      - cp deploy.yml dist/akashkeycloakshop/browser/

artifacts:
  files:
    - '**/*'
  base-directory: dist/akashkeycloakshop/browser
